[package]
name = "actix-telegram"
version = "0.1.0"
authors = ["Marat Safin <jeizsm@gmail.com>"]

[dependencies]
actix = "0.7.3"
actix-web = { git="https://github.com/jeizsm/actix-web", branch="feature/rustls", features=["rust-tls"] }
futures = "0.1.23"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
tokio = "0.1.7"
log = "0.4.3"
env_logger = "0.5.11"
